budget:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: accountadmin
      database: PRE_PROD_DB
      schema: bronze
      warehouse: analysis_wh
      threads: 8
    prod:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: accountadmin
      database: PROD_DB
      schema: bronze
      warehouse: analysis_wh
      threads: 8
