budget:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: accountadmin
      database: budget_dbt_db
      schema: dev
      warehouse: budget_dbt_wh
      threads: 8
    prod:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: accountadmin
      database: budget_dbt_db
      schema: prod
      warehouse: budget_dbt_wh
      threads: 8
